// Load font file and convert to base64
export const MorbitroneFontBase64 =
  "AAEAAAAPADAAAwDAT1MvMkMXKQwAAAD8AAAAVlBDTFRQbHRzAAABVAAAADZjbWFwAN0CfwAAAYwAAAFCY3Z0IAZvBnUAAALQAAAALGZwZ20w9Z6VAAADAAAAAWRnYXNwAAAAEAAAA9gAAAAIZ2x5ZqGv5MoAAAPhAAACxGhlYWQG+PvBAAAN3AAAADZoaGVhBqUIEwAADhQAAAAkaG10eAUkAfAAAA44AAAAGGxvY2EBBgE6AAAPUAAAABBtYXhwAQgA/QAAD2AAAAAgbmFtZRwBGi0AAA+AAAAAm3Bvc3QAAwAAAAARIAAAACBwcmVwQB5LOgAAEUAAAABvAAEAAAABAADLFAlsXw889QADA+gAAAAA1QEE6QAAAADVAQTp/9D/YAN7A0gAAAADAAIAAAAAAAAAAQAAA2z+7gAAAoD/0P/QA3sAAQAAAAAAAAAAAAAAAAAAAAQAAQAAAAQAGAADAAAAAAACAAAAAQABAAAAQAAAAAAAAAACBAEDAAEAAAAAAAABBAEDAAEAAAAAAAABBAEBAAUAAAAAAAADAAAAAAAAAAMAAAAAAwAAAAAAAAAIABAAAQAAAAAAAQAMAAEAAAAAAAIAAQABAAUAAAAAAAADAAEAAQABAAAAAAAEAAIAAwAAAAAAAAIEAgEAAQAAAAAAAAEEAgEAAQAAAAAAAAEEAgEAAAAAAAABAAAAAQAAAAAAAAABAAEAAAABAAAAAQAMAE8AAAAMAAAAAAAAA+gAAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQ=="; // Your base64 encoded font data

export function injectFontStyles(html: string): string {
  return html.replace(
    /@font-face\s*{[^}]*}/g,
    `@font-face {
      font-family: 'Morbitrone';
      src: url(data:application/x-font-woff;charset=utf-8;base64,${MorbitroneFontBase64}) format('woff');
      font-weight: normal;
      font-style: normal;
    }`
  );
}
